CREATE TABLE IF NOT EXISTS youi_dmp_database (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(200) NOT NULL,
  caption VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS youi_dmp_table (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(200) NOT NULL,
  table_name VARCHAR(200) NOT NULL,
  caption VARCHAR(200) NOT NULL
);