[package]
name = "youi-search"
version = "1.0.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tantivy = "0.18.0"
tantivy-jieba = "0.6.0"
cang-jie = "0.14.0"
jieba-rs = "0.6.6"